<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog" Version="4.4.0" />
    <PackageReference Include="Serilog.Sinks.MSSqlServer" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AppStatusCode\AppStatusCode.csproj" />
    <ProjectReference Include="..\DataTransferObjects\DataTransferObjects.csproj" />
    <ProjectReference Include="..\DomainModel\DomainModel.csproj" />
    <ProjectReference Include="..\EncryptionSvc\EncryptionSvc.csproj" />
    <ProjectReference Include="..\LayerData\LayerData.csproj" />
  </ItemGroup>

</Project>
